#!/usr/bin/env python3
"""把 data/*.json 转成浏览器 <script src> 可直接加载的 data/*.js。

浏览器以 file:// 打开页面时 fetch JSON 会被 CORS 拦截，
因此将 JSON 内嵌为 window.__PROCESSES__ / window.__FORMULAS__ 全局变量。
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE.parent / "data"

JOBS = [
    ("processes.json", "processes.js", "__PROCESSES__"),
    ("formulas.json", "formulas.js", "__FORMULAS__"),
]


def main():
    for src_name, dst_name, var in JOBS:
        src = DATA / src_name
        dst = DATA / dst_name
        payload = json.loads(src.read_text(encoding="utf-8"))
        text = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        dst.write_text(
            "// AUTO-GENERATED by tools/embed_data.py — do not edit by hand\n"
            f"window.{var} = {text};\n",
            encoding="utf-8",
        )
        print(f"[embed_data] {src_name} -> {dst_name} ({dst.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
